### PR TITLE
Adding correction for multigraph aspect

### PR DESCRIPTION
**Pull request by Forbu**

### CODE REVIEW

**Comment by ksbeattie** [comment]
@Forbu, can you provide more details on what these changes fix or add?

**Comment by Forbu** [comment]
@ksbeattie Pardon me for the lack of details !
I was trying to make the multigraph MGN work for my own project and I found your cool repo (which work really well).
So I make some modifications to make the "multigraph" part work (it wasn't working previously).

1. I made some correction on some class initializator because we have to initiate the nn module class : I just uncomment the "super" initializator.
2. Also they was an issue because we didn't have the EdgeProcessor in a module list : the EdgeProcessor list was an module attribute of another module but without being in a moduleList ... I made the correction on that.
3. Also they was an issue when all the nodes were not pass in the edge_index / edge attribute : it could generate an error ... I made the correction by passing the number of edge in the scatter sum (dim_size param) inside the node processor loop.

**Comment by ksbeattie** [comment]
@pn51 a/o @bbartoldson can you comment on this?

**Comment by pn51** [comment]
I'll take a look.

**Review by pn51 — APPROVED** [review]

**Comment by ksbeattie** [comment]
@pn51 are we waiting on another review from @bbartoldson or is this ok to merge now?

**Review by bbartoldson — APPROVED** [review]

**Pull request merged**
